name: 'Code Checks'
description: 'Run tests, linting, and other common jobs'
runs:
  using: 'composite'
  steps:
    - name: Install yarn dependencies
      run: yarn --frozen-lockfile
      shell: bash
    - name: Lint
      run: yarn lint
      shell: bash
    - name: Generate types
      run: yarn types
      shell: bash
    - name: Typecheck
      run: yarn typecheck
      shell: bash
